import {
  Layers, Mic, Upload, Search, Zap, RefreshCw, ArrowLeft, Settings,
  X, Terminal, ChevronUp, ChevronDown, Code, Monitor, Link, Globe,
  Filter, Cpu, Github, Linkedin, BookOpen, Loader2, MessageSquare,
  GraduationCap, Briefcase, Layout, User, Send, Shuffle, Award, FileText,
  Microscope, Newspaper, Download, Share2, Undo2, Check,
  Plus,
  Loader
} from 'lucide-react';

export const ICONS = {
  Layers: (props: any) => <Layers {...props} />,
  Mic: (props: any) => <Mic {...props} />,
  Upload: (props: any) => <Upload {...props} />,
  Search: (props: any) => <Search {...props} />,
  Zap: (props: any) => <Zap {...props} />,
  Refresh: (props: any) => <RefreshCw {...props} />,
  ArrowLeft: (props: any) => <ArrowLeft {...props} />,
  Settings: (props: any) => <Settings {...props} />,
  X: (props: any) => <X {...props} />,
  Terminal: (props: any) => <Terminal {...props} />,
  ChevronUp: (props: any) => <ChevronUp {...props} />,
  ChevronDown: (props: any) => <ChevronDown {...props} />,
  Code: (props: any) => <Code {...props} />,
  Monitor: (props: any) => <Monitor {...props} />,
  Link: (props: any) => <Link {...props} />,
  Globe: (props: any) => <Globe {...props} />,
  Filter: (props: any) => <Filter {...props} />,
  Cpu: (props: any) => <Cpu {...props} />,
  Remix: (props: any) => <Shuffle {...props} />,
  Github: (props: any) => <Github {...props} />,
  Linkedin: (props: any) => <Linkedin {...props} />,
  Blog: (props: any) => <BookOpen {...props} />,
  Loader: (props: any) => <Loader {...props} className={`animate-spin ${props.className || ''}`} />,
  Testimonial: (props: any) => <MessageSquare {...props} />,
  Education: (props: any) => <GraduationCap {...props} />,
  Experience: (props: any) => <Briefcase {...props} />,
  Layout: (props: any) => <Layout {...props} />,
  Identity: (props: any) => <User {...props} />,
  Deploy: (props: any) => <Send {...props} />,
  Award: (props: any) => <Award {...props} />,
  CaseStudy: (props: any) => <Microscope {...props} />,
  Publication: (props: any) => <FileText {...props} />,
  Journal: (props: any) => <Newspaper {...props} />,
  Download: (props: any) => <Download {...props} />,
  Share: (props: any) => <Share2 {...props} />,
  Undo: (props: any) => <Undo2 {...props} />,
  Check: (props: any) => <Check {...props} />,
  Plus: (props: any) => <Plus {...props} />
};
